### ISSUE TITLE
Can you show the pycaffe code to generate the train/test.prototxt

### ISSUE THREAD

**Issue by guiyang882** [canteen-man/MobileNet-SSD-Focal-loss#1]
hi @canteen-man ,
thank you for sharing your code, could show me how to use pycaffe to generate the *.prototxt file?
It can help us to modified the model easily.

thx

**Comment by canteen-man** [comment]
@liuguiyangnwpu  sorry ,I don't use pycaffe to  generate the *.prototxt file,I just use the SSD python file to generate the *.prototxt file and modified the model.And I have found a lot of question about this project,I still research this project.

**Comment by guiyang882** [comment]
@canteen-man , I also want to do this work. But now, I guess i want to add selu into the detection network, after several days later, i want to learn how to add the focal loss to the SSD or Mobile SSD.

**Comment by canteen-man** [comment]
@liuguiyangnwpu  原来是中国人，这就方便多了。我是拿ssd的python生成的prototxt然后改的前端mobilenet。在ssd中用focal loss我是参照别人的代码加入的，读了一遍代码，觉得和论文说的意思是一致的，但不知道为什么mAP没有任何提升。如果你能对focal loss加入ssd有什么好办法，也告诉我一下。我现在用shufflenet做前端尝试，没有继续是mobilenet了。

**Comment by guiyang882** [comment]
我看了下Wei Liu大神的issue讨论区，其中看了下关于focal loss的相关评论信息。[Focal Loss with ssd](https://github.com/weiliu89/caffe/issues/720)

**Comment by guiyang882** [comment]
我把MobileNet的网络结构按照pycaffe的方式进行编写，可以通过python进行修改网络结构。
问下MobileNet在不加focal loss时，在VOC07上test的mAP是多少？我训练了一晚上，感觉好低呀？

**Comment by guiyang882** [comment]
基本放弃了MobileNet的训练，感觉运算量没降下来啦！！！

**Comment by canteen-man** [comment]
Channel Pruning for Accelerating Very Deep Neural Networks，我研究这篇论文呢，肯定能加速。
mobilenet我在arm上跑了，有加速效果。

**Comment by canteen-man** [comment]
Channel Pruning for Accelerating Very Deep Neural Networks，我研究这篇论文呢，肯定能加速。
mobilenet我在arm上跑了，有加速效果。

**Comment by guiyang882** [comment]
问下你的MobileNet在VOC上的训练loss是多少？
我的一致徘徊在6.5左右。
我现在开始研究InceptionV3和SSD的结合，感觉VGG模型太大了。
你邮箱是啥，我们可以互相交流？
liuguiyangnwpu@163.com

**Comment by dlyldxwl** [comment]
@liuguiyangnwpu @canteen-man 
我用shicai的mobilenet然后结合ssd训练过，在VOC0712上训练，70多的map
但是在kitti上训得时候map一直只有51左右。
此外shufflenet_ssd我先用coco训练，但是到4w多代，map只有18，想问一下 @canteen-man 你的预训练模型自己训的嘛，结果怎么样呢
也不知道mobilenet v2什么时候能出个caffe版本下的较好的训练结果。

**Comment by canteen-man** [comment]
@dlyldxwl  @liuguiyangnwpu KITTI的数据集我也训练了，那个数据集本来就较为复杂，拿vgg的ssd也就60多的map。我现在在看channel pruning 但我python不是很好，所以进度缓慢。

**Comment by canteen-man** [comment]
@liuguiyangnwpu @dlyldxwl ，我微信号是iron-man747112077，以后可以多交流。

**Comment by dlyldxwl** [comment]
@canteen-man @liuguiyangnwpu 
我做三类的检测（汽车，行人，骑自行车的人）分析了一下kitti的分布，发现这三类分布极不均衡，shuffle作用不明显，然后我加了1000张左右图片扩充了，再用VGG_SSD训练，结果好多了，总的map能达到78多，car的map能达到88（11point下），采用积分算的话，map91，如果你需要提升精度的话，可以按照我说的试一下，预训练模型用coco40w代的模型

**Comment by canteen-man** [comment]
@dlyldxwl  kitti我也训练了，我们俩应该都是按照那个博客做的数据集，我也是3类，但我没有额外加数据。因为我想在树莓派上泡，所以控制模型大小在25M左右，特征提取能力肯定差很多。

**Comment by dlyldxwl** [comment]
@canteen-man
你说的那个博客是我师兄的博客，基本上我项目的进度他都更新在他的博客了，我没怎么细写

**Comment by guiyang882** [comment]
@dlyldxwl 谢谢啦！我导师现在不让我用无人车数据，我现在在研究另外一个领域！我有空把你的实验浮现下，数据增强确实很有用。
