### ISSUE TITLE
bad accuracy

### ISSUE THREAD

**Issue by fgxfxpfzzfcc** [canteen-man/MobileNet-SSD-Focal-loss#2]
Hello, Thank you for sharing your code, is this your best training code? I ran your code results are poor, only 62.5%, may I ask what is the reason?

**Comment by canteen-man** [comment]
并不是最好的结构，你可以继续尝试加入更多的深度可分离卷积，但模型尺寸肯定更大。这个好像记得这个是能在树莓派3上运行的最大模型吧。
