### ISSUE TITLE
focal-loss effective ?

### ISSUE THREAD

**Issue by birdwcp** [canteen-man/MobileNet-SSD-Focal-loss#3]
Comparing with hard example mining ,  Do you think focal-loss is more effective ?  could it bring lower false detection rate in your experimental results?

**Comment by canteen-man** [comment]
focal loss层是我拷贝别人实现的，效果确实不好，但看代码感觉又和论文没区别。何凯明最近开源了focal loss的代码，我还没有看，你可以去看看那个

**Comment by gaojie0105** [comment]
用这个loss应该把ssd中的hard negative mining
